title : 'Flower Garden Banks National Marine Sanctuary Dashboard'
description: 'Flower Garden Banks National Marine Sanctuary Dashboard'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
gems:
  - jekyll-babel
